name: stack dropping worker

on:
  pull_request:
    branches:
      - main
    paths:
      - worker/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: install dependencies
        run: npm ci
        working-directory: worker

      - name: lint
        run: eslint .
        working-directory: worker
